version: "3.7"
services:
  zookeeper:
    image: zookeeper
    networks:
      - lab

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka  
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=common:1:1
    networks:
      - lab
      
  loger:
    image: logerkafka     
    depends_on:
      - kafka
    networks:
      - lab
    restart: always  
      
  checker:
    image: checkerkafka
    depends_on:
     - kafka
    networks:
      - lab    
    restart: always
    environment:
      PYTHONUNBUFFERED: '1'    

networks:
  lab:
    name: lab
    external: true

